import { EquipmentItem } from './types';

export const mockEquipmentData: EquipmentItem[] = [
  // HVAC - Rooftop Units
  {
    id: 'rtu-1',
    tag: 'RTU-1',
    name: 'Trane RTU-8A',
    model: 'YCD120C3H0AA',
    category: 'hvac',
    specs: ['10 Ton', 'Gas Heat'],
    specSection: '23 74 13',
    quantity: 8,
  },
  {
    id: 'rtu-2',
    tag: 'RTU-2',
    name: 'Trane RTU-12B',
    model: 'YCD150C3H0BA',
    category: 'hvac',
    specs: ['12.5 Ton', 'Electric Heat'],
    specSection: '23 74 13',
    quantity: 4,
  },
  {
    id: 'rtu-3',
    tag: 'RTU-3',
    name: 'Carrier 48TC',
    model: '48TC-D16A2A5A0A0G0',
    category: 'hvac',
    specs: ['15 Ton', 'Gas Heat'],
    specSection: '23 74 13',
    quantity: 2,
  },
  // HVAC - VAV Boxes
  {
    id: 'vav-1',
    tag: 'VAV-SD',
    name: 'Trane VAV-SD',
    model: 'VCFC-06',
    category: 'hvac',
    specs: ['600 CFM', 'HW Reheat'],
    specSection: '23 36 00',
    quantity: 24,
  },
  {
    id: 'vav-2',
    tag: 'VAV-MD',
    name: 'Trane VAV-MD',
    model: 'VCFC-10',
    category: 'hvac',
    specs: ['1000 CFM', 'Electric Reheat'],
    specSection: '23 36 00',
    quantity: 16,
  },
  {
    id: 'vav-3',
    tag: 'VAV-LG',
    name: 'Trane VAV-LG',
    model: 'VCFC-14',
    category: 'hvac',
    specs: ['1400 CFM', 'HW Reheat'],
    specSection: '23 36 00',
    quantity: 8,
  },
  // HVAC - Exhaust Fans
  {
    id: 'ef-1',
    tag: 'EF-1',
    name: 'Greenheck CSP-A',
    model: 'CSP-A390',
    category: 'hvac',
    specs: ['1200 CFM', '0.5" SP'],
    specSection: '23 34 23',
    quantity: 6,
  },
  {
    id: 'ef-2',
    tag: 'EF-2',
    name: 'Greenheck CSP-B',
    model: 'CSP-B490',
    category: 'hvac',
    specs: ['2500 CFM', '0.75" SP'],
    specSection: '23 34 23',
    quantity: 4,
  },
  {
    id: 'ef-3',
    tag: 'EF-3',
    name: 'Greenheck RBE',
    model: 'RBE-8-3',
    category: 'hvac',
    specs: ['800 CFM', 'Bathroom'],
    specSection: '23 34 23',
    quantity: 12,
  },
  // HVAC - Air Handling Units
  {
    id: 'ahu-1',
    tag: 'AHU-1',
    name: 'Trane M-Series',
    model: 'MCCB050',
    category: 'hvac',
    specs: ['5000 CFM', 'CHW Coil'],
    specSection: '23 73 00',
    quantity: 2,
  },
  {
    id: 'ahu-2',
    tag: 'AHU-2',
    name: 'Carrier 39M',
    model: '39MW08',
    category: 'hvac',
    specs: ['8000 CFM', 'DX Cooling'],
    specSection: '23 73 00',
    quantity: 1,
  },
  // HVAC - Split Systems
  {
    id: 'split-1',
    tag: 'AC-1',
    name: 'Mitsubishi MXZ',
    model: 'MXZ-4C36NAHZ',
    category: 'hvac',
    specs: ['36000 BTU', 'Multi-Zone'],
    specSection: '23 81 26',
    quantity: 3,
  },
  {
    id: 'split-2',
    tag: 'AC-2',
    name: 'Daikin VRV',
    model: 'RXYQ72TTJU',
    category: 'hvac',
    specs: ['6 Ton', 'Heat Recovery'],
    specSection: '23 81 26',
    quantity: 2,
  },
  // HVAC - Unit Heaters
  {
    id: 'uh-1',
    tag: 'UH-1',
    name: 'Modine HD',
    model: 'HD100',
    category: 'hvac',
    specs: ['100 MBH', 'Gas Fired'],
    specSection: '23 83 16',
    quantity: 8,
  },
  // Plumbing - Pumps
  {
    id: 'pump-1',
    tag: 'P-1',
    name: 'Bell & Gossett e-1510',
    model: '1510-3BB',
    category: 'plumbing',
    specs: ['150 GPM', '40 ft HD'],
    specSection: '22 11 19',
    quantity: 2,
  },
  {
    id: 'pump-2',
    tag: 'P-2',
    name: 'Grundfos CR',
    model: 'CR 15-3',
    category: 'plumbing',
    specs: ['75 GPM', '120 ft HD'],
    specSection: '22 11 19',
    quantity: 1,
  },
  {
    id: 'pump-3',
    tag: 'CP-1',
    name: 'Taco 4400',
    model: '4400-T3-3',
    category: 'plumbing',
    specs: ['50 GPM', 'Circulator'],
    specSection: '22 11 19',
    quantity: 4,
  },
  // Plumbing - Water Heaters
  {
    id: 'wh-1',
    tag: 'WH-1',
    name: 'A.O. Smith BTH',
    model: 'BTH-500A',
    category: 'plumbing',
    specs: ['500 MBH', '130 Gal'],
    specSection: '22 33 00',
    quantity: 2,
  },
  {
    id: 'wh-2',
    tag: 'WH-2',
    name: 'Rheem Tankless',
    model: 'RTGH-RH11',
    category: 'plumbing',
    specs: ['199 MBH', 'Condensing'],
    specSection: '22 33 00',
    quantity: 3,
  },
  // Plumbing - Fixtures
  {
    id: 'fix-1',
    tag: 'WC-1',
    name: 'Kohler Highline',
    model: 'K-25224',
    category: 'plumbing',
    specs: ['1.28 GPF', 'ADA'],
    specSection: '22 42 13',
    quantity: 24,
  },
  {
    id: 'fix-2',
    tag: 'LAV-1',
    name: 'Kohler Memoirs',
    model: 'K-2269-8',
    category: 'plumbing',
    specs: ['Pedestal', 'ADA'],
    specSection: '22 42 16',
    quantity: 18,
  },
  // Electrical - Panels
  {
    id: 'panel-1',
    tag: 'MDP',
    name: 'Square D I-Line',
    model: 'HCP23684',
    category: 'electrical',
    specs: ['1600A', '480/277V'],
    specSection: '26 24 16',
    quantity: 1,
  },
  {
    id: 'panel-2',
    tag: 'LP-1',
    name: 'Square D NQ',
    model: 'NQ442L2',
    category: 'electrical',
    specs: ['225A', '208/120V'],
    specSection: '26 24 16',
    quantity: 6,
  },
  {
    id: 'panel-3',
    tag: 'PP-1',
    name: 'Square D NQ',
    model: 'NQ430L1',
    category: 'electrical',
    specs: ['100A', '208/120V'],
    specSection: '26 24 16',
    quantity: 8,
  },
  // Electrical - Transformers
  {
    id: 'xfmr-1',
    tag: 'T-1',
    name: 'Square D EE75T3H',
    model: 'EE75T3H',
    category: 'electrical',
    specs: ['75 kVA', '480-208/120V'],
    specSection: '26 22 00',
    quantity: 3,
  },
  {
    id: 'xfmr-2',
    tag: 'T-2',
    name: 'Square D EE150T3H',
    model: 'EE150T3H',
    category: 'electrical',
    specs: ['150 kVA', '480-208/120V'],
    specSection: '26 22 00',
    quantity: 1,
  },
  // Electrical - Generators
  {
    id: 'gen-1',
    tag: 'G-1',
    name: 'Generac SG250',
    model: 'SG250',
    category: 'electrical',
    specs: ['250 kW', 'Diesel'],
    specSection: '26 32 13',
    quantity: 1,
  },
  // Electrical - UPS
  {
    id: 'ups-1',
    tag: 'UPS-1',
    name: 'Eaton 93PM',
    model: '93PM-50',
    category: 'electrical',
    specs: ['50 kVA', 'Online'],
    specSection: '26 33 53',
    quantity: 2,
  },
  // Fire Protection - Pumps
  {
    id: 'fp-1',
    tag: 'FP-1',
    name: 'Aurora Fire Pump',
    model: '481-15A',
    category: 'fire-protection',
    specs: ['500 GPM', '100 PSI'],
    specSection: '21 12 00',
    quantity: 1,
  },
  {
    id: 'fp-2',
    tag: 'JP-1',
    name: 'Aurora Jockey',
    model: '361-8A',
    category: 'fire-protection',
    specs: ['20 GPM', '125 PSI'],
    specSection: '21 12 00',
    quantity: 1,
  },
  // Fire Protection - Alarm Panel
  {
    id: 'facp-1',
    tag: 'FACP',
    name: 'Notifier NFS2-3030',
    model: 'NFS2-3030',
    category: 'fire-protection',
    specs: ['Addressable', '6 Loops'],
    specSection: '28 31 11',
    quantity: 1,
  },
];

// Group equipment by category
export const groupEquipmentByCategory = (items: EquipmentItem[]) => {
  return items.reduce((acc, item) => {
    if (!acc[item.category]) {
      acc[item.category] = [];
    }
    acc[item.category].push(item);
    return acc;
  }, {} as Record<string, EquipmentItem[]>);
};

// Get total count
export const getTotalEquipmentCount = (items: EquipmentItem[]) => {
  return items.reduce((sum, item) => sum + item.quantity, 0);
};
